-- yoyo migration
-- transaction: true

CREATE TABLE anidb (
    anidb_id INTEGER PRIMARY KEY,
    display_title TEXT NOT NULL,
    english_title TEXT,
    native_title TEXT,
    start_date TEXT,
    media_type TEXT,
    country TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lain TEXT DEFAULT '[]',
    allcinema TEXT DEFAULT '[]',
    amazon_prime_video TEXT DEFAULT '[]',
    amazon_video TEXT DEFAULT '[]',
    animemorial TEXT DEFAULT '[]',
    animenewsnetwork TEXT DEFAULT '[]',
    animenfo TEXT DEFAULT '[]',
    anison TEXT DEFAULT '[]',
    baidu_baike TEXT DEFAULT '[]',
    bangumi TEXT DEFAULT '[]',
    bilibili TEXT DEFAULT '[]',
    chinese_wikipedia TEXT DEFAULT '[]',
    crunchyroll TEXT DEFAULT '[]',
    douban TEXT DEFAULT '[]',
    english_wikipedia TEXT DEFAULT '[]',
    facebook TEXT DEFAULT '[]',
    funimation TEXT DEFAULT '[]',
    hidive TEXT DEFAULT '[]',
    imdb TEXT DEFAULT '[]',
    japanese_wikipedia TEXT DEFAULT '[]',
    korean_wikipedia TEXT DEFAULT '[]',
    marumegane TEXT DEFAULT '[]',
    media_art_database TEXT DEFAULT '[]',
    myanimelist TEXT DEFAULT '[]',
    netflix TEXT DEFAULT '[]',
    official_blog TEXT DEFAULT '[]',
    official_english_website TEXT DEFAULT '[]',
    official_stream TEXT DEFAULT '[]',
    official_website TEXT DEFAULT '[]',
    qq TEXT DEFAULT '[]',
    syoboi TEXT DEFAULT '[]',
    tmdb TEXT DEFAULT '[]',
    tv_animation_museum TEXT DEFAULT '[]',
    twitter TEXT DEFAULT '[]',
    visual_novel_database TEXT DEFAULT '[]',
    youtube TEXT DEFAULT '[]'
);

-- rollback: DROP TABLE anidb;
