name: "Fetch Future Seasons"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at 00:00 UTC (weekly)

permissions:
  contents: write

jobs:
  fetch:
    name: Fetch Seasonal Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch future seasonal data
        run: python3 scripts/fetch_future_seasons.py

      - name: Commit and push changes
        run: |
          if [[ -n $(git status --porcelain database/raw/sideload_future.json) ]]; then
            git config --local user.email "nattadasu@nattadasu.my.id"
            git config --local user.name "Natsu Tadama"
            git add database/raw/sideload_future.json
            git commit -m "Automated fetch of future seasonal data"
            git push
          else
            echo "No changes in seasonal data"
          fi
